### ISSUE TITLE
Spell Check completely off.

### ISSUE THREAD

**Issue by Lockehart** [LadyDefile/Wordsmith-DalamudPlugin#36]
This issue started within the past few days.  Spell check is scanning things completely off.  It's scanning between two words, counting it as one word and reporting it for a spelling error.  For example I can have 'you're gonna go right?' in a sentence and it'll read between 'you're gonna' , highlight ' 're go' as a word and mark it as misspelled.  Idk what's causing it.  I've reloaded dictionaries, swapped back and forth, reset settings to default, completely reinstalled and it's the same issue.  I'm currently on version 1.8.0

**Comment by Lockehart** [comment]
Ahh saw a previously closed issue too late.  I didn't think it was still an active bug since it was closed.  My bad!

**Comment by LadyDefile** [comment]
No worries! Nothing wrong with posting a bug that you notice, even if someone already put it here. The more posts I see about something and the more information I get from people, the easier problems are to solve. But yea, this particular issue is fixed and v1.8.1 is out now in testing. Feel free to grab it from the testing branch and give it try.

I also implemented a new quality assurance protocol that I'll be using to make sure major bugs like this don't make it past me anymore as much as I can. My goal is to get 1.8.1 to be the current stable version as soon as possible but before I can do that I want to make sure it's in testing for a few days first.

I'll leave this issue report here for now in case anyone else stops by with the same issue. Don't be afraid to leave another report if anything else does come up that I haven't fixed!

**Comment by LadyDefile** [comment]
As an aside, really sorry about the issue. I'm not sure how I ended up releasing a patch with such an obvious and huge bug in it! I've put some protocols in place to ensure this doesn't happen in the future. It's really embarrassing to have something like this fall through the cracks.

**Comment by Aniotid** [comment]
![image](https://user-images.githubusercontent.com/107821003/210670454-4e155c31-af3d-4002-8405-9fdba3c81a7c.png)

Not fixed yet unfortunately, as of today's update--

Wordsmith version: v1.7.7
Number of scratchpads open: 1
Logs: probably not necessary, via screenshot
Bug behavior: Spellchecking is behaving strangely where punctuation and spaces are concerned, regardless of whether "Fix spaces" is enabled or disabled. Anywhere with - punctuation, space, start of word - are reporting as spelling errors fairly consistently. It tends to start at the second sentence of any given paragraph, and excludes hyphens, but includes colons/semicolons. Looks like it's specifically starting spellchecks on the punctuation and next 5 characters after or so.

**Comment by LadyDefile** [comment]
@Aniotid So the issue *is* fixed but not in v1.7.7. The issue is fixed in the current testing branch version which is v1.8.1. I've got it in testing at the moment but I should be pushing it to the live version soon. If you want to use v1.8.1 you have to enable testing version for Wordsmith and it will download the latest 1.8.1.

**Comment by LadyDefile** [comment]
In fact, I'll push 1.8.1 to live now. It may take a day or two before the Dalamud teem gets it out but I'll push it now.
